name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: bats-coreをインストールする
      run: |
        git clone https://github.com/bats-core/bats-core.git
        whoami
    - name: テストを実行する
      run: |
        $HOME/bats-core/bin/bats test
