name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: batsをインストールする
      run: |
        (cd; git clone https://github.com/bats-core/bats-core.git)
    - name: テストを実行する
      run: |
        $HOME/bats-core/bin/bats test
